### ISSUE TITLE
Rhe 'Pods-Runner' target has frameworks with conflicting names: mamapkit.framework and amapfoundationkit.framework.

### ISSUE THREAD

**Issue by fidoChou** [fluttify-project/amap_map_fluttify#156]
**this is my podfile**
```

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```
this is pubspec.yaml

```
name: hello_world
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.0
  avatar_glow: ^1.0.0
  cached_network_image: ^1.1.1
  transparent_image: ^1.0.0
  flutter_html: ^0.11.1
  material_search: ^0.2.8
  dio: ^2.1.16
  http: ^0.12.0+2
  cool_ui: "^0.2.1"
  image_picker: 0.6.1+4
  multi_image_picker: 4.5.4
  permission_handler: ^3.2.2
  amap_location: ^0.2.0
  city_pickers: ^0.1.25
  flutter_search_panel: ^1.0.1
  search_widget: ^0.2.0
  floating_search_bar: ^0.2.0
  json_annotation: ^3.0.0
  common_utils: ^1.1.3
  webview_flutter: ^0.3.14+1
  flutter_webview_plugin: ^0.3.8
  jpush_flutter: ^0.1.0
  jmessage_flutter: ^0.5.0
  shared_preferences: ^0.5.3+4
  image_crop: ^0.3.1
  zefyr: ^0.8.0
  font_awesome_flutter: ^8.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.7+1
  fluro: ^1.5.1
  keyboard_actions: ^2.1.2
  oktoast: ^2.2.0
  after_layout: ^1.0.7+2
  flutter_2d_amap:
    git:
      url: https://github.com/simplezhli/flutter_2d_amap.git
  datetime_picker_formfield: 0.4.3
  flutter_tags: ^0.4.5
  flutter_swiper: ^1.1.6
  slide_countdown_clock: ^1.0.3
  line_icons: ^0.2.0
  loadmore: ^1.0.4
  flutter_image_compress: ^0.6.3
  device_info: ^0.4.1+3
  path_provider: ^1.3.1
  simple_image_crop: 0.1.1
  like_button: ^0.1.9
  uni_links: ^0.2.0
  amap_map_fluttify: 0.10.5+be1d1e5
  flutter_stack_card: 0.2.0+1
  swipe_stack: ^1.0.0
  selectable_circle: 0.1.6+4
  intro_slider: ^2.2.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_launcher_icons:

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/1024.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/activity/
    - assets/images/intro/
    - assets/images/splash/
    - raw/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

flutter --version:
`Flutter 1.9.1+hotfix.5`

pod --version
`1.8.4`

**Comment by yohom** [comment]
```yaml
flutter_2d_amap:
  git:
    url: https://github.com/simplezhli/flutter_2d_amap.git
```
也是高德地图SDK吗？
