### ISSUE TITLE
Because no versions of amap_search_fluttify match >0.7.9+481e45c <0.8.0 and amap_search_fluttify 0.7.9+481e45c

### ISSUE THREAD

**Issue by 415593725** [fluttify-project/amap_map_fluttify#208]
这两个一起用出现问题
amap_map_fluttify: ^0.19.1+b2681d9
amap_search_fluttify: ^0.7.9+481e45c

Because no versions of amap_search_fluttify match >0.7.9+481e45c <0.8.0 and amap_search_fluttify 0.7.9+481e45c depends on foundation_fluttify ^0.4.14+2, amap_search_fluttify ^0.7.9+481e45c requires foundation_fluttify ^0.4.14+2.

And because amap_map_fluttify >=0.19.0+b2681d9 depends on foundation_fluttify ^0.5.0, amap_search_fluttify ^0.7.9+481e45c is incompatible with amap_map_fluttify >=0.19.0+b2681d9.

So, because catfish depends on both amap_map_fluttify ^0.19.1+b2681d9 and amap_search_fluttify ^0.7.9+481e45c, version solving failed.
pub get failed (1; So, because catfish depends on both amap_map_fluttify ^0.19.1+b2681d9 and amap_search_fluttify ^0.7.9+481e45c, version solving failed.)

**Comment by yohom** [comment]
```yaml
amap_search_fluttify: ^0.8.0+b2681d9
amap_location_fluttify: ^0.10.0+e74b91b
amap_map_fluttify: ^0.19.1+b2681d9
```
这三个版本可以共存，如果你要简单点就直接依赖amap_all_fluttify。
